mvynokur: added Google test to verify search
JavaTestAutomation704/selenide_tasks_704 pull request #1
Opened 2022-08-04 13:22 UTC by MyroslavaVynokur

2022-08-05 06:25 UTC, toleksyn requested changes

2022-08-05 06:25 UTC, toleksyn commented on src/test/java/mvynokur/GoogleTest.java
> +    public void setUp() {
rename

2022-08-05 06:25 UTC, toleksyn commented on src/test/java/mvynokur/GoogleTest.java
> +    public void verify_firstLink_contains_dogs() {
rename

2022-08-08 16:07 UTC, toleksyn commented on src/main/java/mvynokur/GooglePage.java
> +    private final String UkrainianLanguageLink = "//div[@id = 'SIvCob']/a[contains(text(), 'українська')]";
no cyrillic in locators

2022-08-08 16:08 UTC, toleksyn commented on src/main/java/mvynokur/SearchResultsPage.java
> +    public ElementsCollection searchResultLinksNames() {
rename

2022-08-08 16:08 UTC, toleksyn commented on src/test/java/mvynokur/GooglePageBaseMethods.java
> +public class GooglePageBaseMethods {
???

2022-08-08 16:09 UTC, toleksyn commented on src/test/java/mvynokur/GoogleTest.java
> +        SearchResultsPage results = new SearchResultsPage();
no raw page objects in tests

2022-08-09 05:32 UTC, toleksyn commented on src/main/java/mvynokur/GooglePage.java
> +    private final String languageBlock = "//div[@id='SIvCob']";
why are these fields if they are being used once?

2022-08-09 05:32 UTC, toleksyn commented on src/main/java/mvynokur/GooglePage.java
> +
rename

2022-08-09 05:32 UTC, toleksyn commented on src/main/java/mvynokur/GooglePage.java
> +        return new GooglePage();
no need to create new object

2022-08-09 05:32 UTC, toleksyn commented on src/main/java/mvynokur/SearchResultsPage.java
> +    private final String linkName = "//h3[@class = 'LC20lb MBeuO DKV0Md']";
rename

2022-08-09 05:32 UTC, toleksyn commented on src/main/java/mvynokur/SearchResultsPage.java
> +    }
PO should only have action methods and methods, that return data

2022-08-09 05:32 UTC, toleksyn commented on src/test/java/mvynokur/BaseTestRunner.java
> +        open("https://www.google.com");
breaks PO model

2022-08-09 05:32 UTC, toleksyn commented on src/test/java/mvynokur/GoogleTest.java
> +    public void verifyNavigationToHomePage() throws InterruptedException {
why is this throws needed?

2022-08-09 05:32 UTC, toleksyn commented on src/test/java/mvynokur/GoogleTest.java
> +    public void verifyNavigationToHomePage() throws InterruptedException {
why is this throws needed?

2022-08-09 05:33 UTC, toleksyn requested changes

2022-08-09 05:33 UTC, toleksyn commented on src/main/java/mvynokur/GooglePage.java
> +    public GooglePage logoIconIsVisible() {
Java code convention: isLogoVisible() and should return a boolean

2022-08-09 22:27 UTC, dankomax commented on src/test/java/mvynokur/BaseTestRunner.java
> +        searchResults = new SearchResultsPage();
Should be searchResultsPage = new SearchResultsPage();

2022-08-10 05:26 UTC, toleksyn requested changes

2022-08-10 05:26 UTC, toleksyn commented on src/main/java/mvynokur/GooglePage.java
> +        } catch (ElementNotFound e) {
does this really work?

2022-08-10 05:26 UTC, toleksyn commented on src/main/java/mvynokur/SearchResultsPage.java
> +    public int amountOfLinks() {
rename, get*()

2022-08-10 05:26 UTC, toleksyn commented on src/main/java/mvynokur/SearchResultsPage.java
> +    public String getDescriptionTextByLinkNumber(int number) {
rename, getDescriptionText(int linkNumber)

2022-08-11 05:25 UTC, toleksyn requested changes

2022-08-11 05:25 UTC, toleksyn commented on src/main/java/mvynokur/GooglePage.java
> +    public GooglePage openHomePage() {
rename

2022-08-11 06:23 UTC, toleksyn requested changes

2022-08-11 06:23 UTC, toleksyn commented on src/test/java/mvynokur/GoogleTest.java
> +    public void verifyNineLinkURLCorrectness() {
camel case

2022-08-12 05:25 UTC, toleksyn requested changes

2022-08-12 05:25 UTC, toleksyn commented on src/test/java/mvynokur/BaseTestRunner.java
> +    protected SearchResultsPage searchResultsPage = new SearchResultsPage();
you should get this from a PO method call

2022-08-15 05:45 UTC, toleksyn requested changes

2022-08-15 05:45 UTC, toleksyn commented on src/main/java/mvynokur/SearchResultsPage.java
> +        return $$x("//div[@class = 'Uroaid']").get(linkNumber - 1).text().toLowerCase();
use direct locator

2022-08-15 05:45 UTC, toleksyn commented on src/test/java/mvynokur/GoogleTest.java
> +        searchResultsPage.clearSearchField().searchFor("funny kitten");
format properly

2022-08-15 05:45 UTC, toleksyn commented on src/test/java/mvynokur/GoogleTest.java
> +        softAssert.assertTrue(searchResultsPage.getDescriptionText(1).contains("kitten"));
searchResultsPage.getDescriptionText(1) - extract to var, re-use

2022-08-16 05:25 UTC, merged