dankomax: added PO methods
JavaTestAutomation704/selenide_tasks_704 pull request #31
Opened 2022-08-18 19:48 UTC by dankomax

2022-08-19 05:56 UTC, toleksyn requested changes

2022-08-19 05:56 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/ProductPage.java
> +    public ShoppingCartModal buy() {
rename

2022-08-19 05:56 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/ProductPage.java
> +    public ProductCharacteristicsPage openCharacteristics() {
rename

2022-08-19 05:56 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/SearchResultsPage.java
> +    public SearchResultsPage sortDescByPrice() {
rename

2022-08-19 06:16 UTC, toleksyn requested changes

2022-08-19 06:16 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/components/Header.java
> +    public boolean isShoppingCartEmpty() {
?

2022-08-19 11:54 UTC, dankomax commented on src/main/java/com/softserveinc/ita/rozetka/ProductPage.java
> +    public ShoppingCartModal buy() {
renamed addToCart

2022-08-19 11:54 UTC, dankomax commented on src/main/java/com/softserveinc/ita/rozetka/ProductPage.java
> +    public ProductCharacteristicsPage openCharacteristics() {
renamed openCharacteristicsPage

2022-08-19 11:57 UTC, dankomax commented on src/main/java/com/softserveinc/ita/rozetka/SearchResultsPage.java
> +    public SearchResultsPage sortDescByPrice() {
renamed sortDescendingByPrice
There is only two sorting options we use in our test cases sortDescendingByPrice and sortAscendingByPrice.

2022-08-19 11:57 UTC, dankomax commented on src/main/java/com/softserveinc/ita/rozetka/components/Header.java
> +    public boolean isShoppingCartEmpty() {
renamed isCartIconContainsCounter

2022-08-21 14:37 UTC, toleksyn requested changes

2022-08-21 14:37 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/SearchResultsPage.java
> +    public SearchResultsPage sortDescendingByPrice() {
sortDescending(enum)

2022-08-22 06:12 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/SearchResultsPage.java
> +    public SearchResultsPage sortDescendingByPrice() {
sortByPrice(ascending)

2022-08-22 20:19 UTC, dankomax commented on src/main/java/com/softserveinc/ita/rozetka/SearchResultsPage.java
> +    public SearchResultsPage sortDescendingByPrice() {
created enam ProductSort:
sortBy(PRICE_DESCENDING),
sortBy(POPULARITY), etc.

2022-08-22 20:20 UTC, dankomax commented on src/main/java/com/softserveinc/ita/rozetka/components/Header.java
> +    public boolean isShoppingCartEmpty() {
renamed isShoppingCartCounterVisible()

2022-08-23 05:04 UTC, merged