odashynych: added test to cover sale sort
JavaTestAutomation704/selenide_tasks_704 pull request #51
Opened 2022-08-24 18:26 UTC by clarmmym

2022-08-25 05:18 UTC, toleksyn requested changes

2022-08-25 05:18 UTC, toleksyn commented on src/main/java/com/softserveinc/ita/rozetka/SearchResultsPage.java
> +    public boolean isOnSale(int productNumber) {
this should be in Product class

2022-08-25 05:18 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka/FilterProductTest.java
> +    public void saleSortTest() {
???

2022-08-25 05:18 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka/FilterProductTest.java
> +                .getHeader()
duplication

2022-08-26 05:52 UTC, toleksyn requested changes

2022-08-26 05:52 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka/FilterProductTest.java
> +        softAssert.assertTrue(searchResultsPage.getProduct(59).isOnSale());
what if in the middle of products there's a bug?

2022-08-26 05:52 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka/FilterProductTest.java
> +        softAssert.assertTrue(searchResultsPage.getProduct(59).isOnSale());
what if there's less than 59 products?

2022-08-26 05:52 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka/FilterProductTest.java
> +        softAssert.assertTrue(searchResultsPage.getProduct(60).isOnSale());
same

2022-08-29 05:11 UTC, toleksyn requested changes

2022-08-29 05:11 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka/FilterProductTest.java
> +    public void verifySaleSort() {
rename

2022-08-29 05:11 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka/FilterProductTest.java
> +        Assert.assertTrue(searchResultsPage.getProductsSize() >= 60, "There aren't 60 products");
assertj

2022-08-29 05:11 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka/FilterProductTest.java
> +                .withFailMessage(String.format(errorMessage, productNumber))
.as()

2022-08-29 05:11 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka/FilterProductTest.java
> +        productNumber = 25;
inline these variables

2022-08-29 14:55 UTC, dankomax commented on src/test/java/com/softserveinc/ita/rozetka/FilterProductTest.java
> +    public void verifySaleSort() {
veryfyUserCanSortProductsByPromotion

2022-08-30 05:33 UTC, toleksyn requested changes

2022-08-30 05:33 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka/FilterProductTest.java
> +    public void verifyProductsSortingByPromotion() {
is it sorting or filtering?

2022-08-30 05:33 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka/FilterProductTest.java
> +                .sortBy(ProductSort.RATING)
is it sorting by promotion or rating?

2022-08-31 05:03 UTC, toleksyn requested changes

2022-08-31 05:03 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka/FilterProductTest.java
> +    public void verifyProductsSaleFilter() {
rename

2022-08-31 05:03 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka/FilterProductTest.java
> +                    .as("Product with number %s should be on sale", productNumber)
number + " product should ... "

2022-09-01 05:11 UTC, toleksyn requested changes

2022-09-01 05:11 UTC, toleksyn commented on src/test/java/com/softserveinc/ita/rozetka/SortingProductTest.java
> +        for (int productNumber : new int[]{1, 25, 59}) {
why it's {1, 25, 59} and in the previous test it's {2, 40, 60} ?

2022-09-01 06:41 UTC, merged